travis:
  secure:
    BINSTAR_TOKEN: SITBHvkVWJDB9Qkrg9gSVNYngH+ogXoB1p3Cvw72wxVNOmggk2P+UuZ3/9fUWBxzr153js/tGCZwYKuC9QnP3L/0j1ECEkU/yKmTseGHcE5er5UzTcTaFKCy+JTLiuxm4RqUMxRVdyC2RMMkri4/bSo3DbBOgeto/KySTZXNGiOIYwc01o9VsqdVSWaObcMM8FoaVLTme7jN4cjPLA+PSVmrtKu5hlzrSZ1YEJ3Be9xqqLc0zHStENI4BkAUDG1FjxAfweEVfLUhJTGTVI6/uNXp+aW694ma9L2oM6xueIiprycODvelkMXC+AVkhvxnkgUpx2HJE7gd+TFdtizyC7BAABeTNFCssqWNfUawwRGV6vYKXumek4FMOrskVDaWlJVF5gmu/fpj5l345sfJZW9N/6OBkjMG9tggyfWIEwcnw5EGLmCsb45R4RIzWVF9HFIXpFm/OfTRq7T2S4GkRRuVUchGSK2BIdel+l/oUnpeS6+k9PaDEwYnsoKKCoRMVr3nWjPtOJVdzhgMfkJibZl9L8f5yjRUQYJRIp6yQvJ5Yxps8RTbauR65pQY0TWsO6IAEb91aIDDBsYOM3zoZu5yrRNyo5RWLqftsyKCe0hG/HGE/+QlGGhxJdn65yY24aq+dt+qhs1Rgde/8dvMRpyHhYFVz103HSkEbX9xaAM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
